import type { Locale } from "./types";

export type FaqCategory =
  | "getting_started"
  | "sync"
  | "context"
  | "privacy"
  | "workspaces"
  | "workspaces_sync"
  | "catalog"
  | "integrations"
  | "plans_billing"
  | "platforms"
  | "support";

/** Public FAQ projection. Keep this type intentionally free of editorial metadata. */
export interface PublicFaqItem {
  id: string;
  category: FaqCategory;
  question: string;
  answer: string;
  aliases: string[];
}

const FAQ_BY_LOCALE: Record<Locale, readonly PublicFaqItem[]> = {
  es: [
    { id: "core.what_is", category: "getting_started", question: "¿Qué es TerminalSync?", answer: "TerminalSync reúne tu trabajo con IA en espacios de trabajo que puedes retomar, organizar y sincronizar entre tus equipos. Conserva el contexto del proyecto, las conversaciones, la memoria y las herramientas que hayas conectado para que no tengas que empezar de cero.", aliases: ["para qué sirve","qué hace","cómo funciona"] },
    { id: "core.get_started", category: "getting_started", question: "¿Cómo empiezo?", answer: "Descarga TerminalSync, inicia sesión y crea tu primer espacio de trabajo. La IA incluida queda lista para conversar; después puedes agregar archivos, enlaces o herramientas desde Contexto cuando quieras trabajar con información de tu negocio.", aliases: ["cómo comenzar","primer paso","instalar"] },
    { id: "sync.move_between_devices", category: "workspaces_sync", question: "¿Cómo paso mi trabajo a otro equipo?", answer: "Deja de escribir en el primer equipo, espera a que se sincronice y después abre, importa o retoma ese espacio en el segundo. Así continúas con el historial y el contexto del proyecto.", aliases: ["sincronizar entre computadoras","cambiar de equipo","continuar en otra computadora"] },
    { id: "context.what_is", category: "context", question: "¿Qué es Contexto?", answer: "Contexto es el lugar donde ves qué información puede usar la IA en ese espacio: conversaciones, documentos, notas, reglas, enlaces, videos, memoria y material producido. También separa las herramientas conectadas para que no confundas una conexión con un documento que la IA ya leyó. Controles como pausar, quitar o preguntar solo sobre una fuente aparecen solo cuando esa fuente los permite.", aliases: ["qué está usando la IA","agregar contexto","panel de contexto"] },
    { id: "memory.persistent", category: "workspaces_sync", question: "¿La IA recuerda mi proyecto?", answer: "Sí. TerminalSync sincroniza la memoria de cada proyecto: conversaciones anteriores y notas sobre tus formas de trabajar. Cuando abres el mismo proyecto en otro equipo, puedes continuar con ese contexto en lugar de explicarlo de nuevo.", aliases: ["memoria persistente","la IA se acuerda","no quiero repetir el contexto"] },
    { id: "context.web_and_youtube", category: "context", question: "¿Puedo agregar una página web o un video de YouTube?", answer: "Sí. En Contexto elige “Webs y videos”, pega el enlace y espera a que el texto quede guardado. Un video de YouTube funciona cuando tiene una pista de subtítulos que la aplicación puede leer; si no, el panel debe explicar el problema en vez de fingir que lo leyó.", aliases: ["leer un video","agregar una URL","webs y videos"] },
    { id: "context.share_to_workspace", category: "context", question: "¿Puedo enviar contexto a otro espacio?", answer: "Sí. Selecciona las fuentes que se pueden compartir y envíalas a otro espacio tuyo. En el destino deben aparecer como una copia utilizable; quitar la copia del destino no debe borrar la fuente original.", aliases: ["compartir contexto","pasar documentos a otro espacio","enviar material"] },
    { id: "privacy.what_is_encrypted", category: "privacy", question: "¿Qué queda protegido?", answer: "Tus secretos, credenciales, perfil, memoria y conversaciones con la IA se cifran en tu equipo antes de sincronizarse. Tus archivos de proyecto van a tu propia cuenta de nube en su formato original: no debes confundir esa ruta con el cifrado de las conversaciones y secretos.", aliases: ["seguridad","cifrado","pueden ver mis archivos","privacidad"] },
    { id: "workspaces.offline", category: "workspaces_sync", question: "¿Qué pasa si pierdo internet?", answer: "El trabajo local puede continuar sin conexión y la sincronización con la nube se reanuda cuando vuelves a tener internet. Las funciones que necesitan leer un servicio externo o responder con la IA pueden esperar a que vuelva la conexión.", aliases: ["funciona sin internet","sin conexión","offline"] },
    { id: "catalog.what_are_connectors", category: "integrations", question: "¿Qué es un conector y qué necesito para usarlo?", answer: "Un conector enlaza la IA con un servicio que ya usas, como correo, calendario, documentos, CRM o pagos. Se agrega desde Integraciones y puede requerir una API key, OAuth, inicio de sesión, una cuenta o permisos según el servicio. La pantalla debe decirte qué falta.", aliases: ["integraciones","conectar Gmail","conectar herramientas","qué permisos necesita"] },
    { id: "catalog.five_sections", category: "catalog", question: "¿Qué puedo encontrar en Integraciones?", answer: "El explorador organiza el catálogo en cinco grupos visibles: Kits, Plugins, Conectores, Skills y Herramientas CLI. Los Kits y Plugins juntan piezas para un trabajo; los Conectores enlazan servicios; los Skills aportan una forma de trabajar; y las Herramientas CLI cubren tareas técnicas que necesitan instalación e inicio de sesión.", aliases: ["kits","plugins","herramientas CLI","qué hay en el catálogo","skills"] },
    { id: "catalog.kits_are_included", category: "catalog", question: "¿Los Kits tienen un costo aparte?", answer: "Los Kits disponibles aparecen marcados como gratuitos e incluidos en el plan; algunos están marcados Próximamente y no deben contarse como listos. El costo o la cuenta que necesites para una integración externa dentro del Kit sigue dependiendo de ese servicio.", aliases: ["kits gratis","precio de los kits","packs"] },
    { id: "plans.current_pricing", category: "plans_billing", question: "¿Cuánto cuesta?", answer: "Los planes y la disponibilidad de cualquier prueba aparecen en la pantalla de precios y en el checkout. Revisa el plan actual, la moneda y las condiciones antes de pagar; las cuentas existentes no deben asumir que una prueba se reinicia al cambiar de plan.", aliases: ["precio","planes","prueba gratis","mensualidad","cobro"] },
    { id: "platforms.launch_scope", category: "platforms", question: "¿En qué equipos está disponible ahora?", answer: "El lanzamiento actual es para macOS. Windows está reuniendo personas interesadas mientras termina la firma del instalador, y Linux no forma parte de la promesa pública de este lanzamiento. No anuncies esas plataformas como descargas activas hasta que la dirección lo cambie.", aliases: ["funciona en Windows","funciona en Linux","descarga para Mac","plataformas"] },
    { id: "support.when_human", category: "support", question: "¿Qué hago si algo falla?", answer: "Primero revisa el aviso de la aplicación y vuelve a intentar solo si la acción lo indica. Si hay riesgo de perder datos, un cobro, un problema de seguridad o un fallo repetido de sincronización, pide ayuda humana y conserva el mensaje de error sin compartir secretos.", aliases: ["ayuda","no funciona","hablar con una persona","perdí datos"] },
  ],
  en: [
    { id: "core.what_is", category: "getting_started", question: "What is TerminalSync?", answer: "TerminalSync brings your AI work together in workspaces that you can resume, organize, and sync between your devices. It keeps your project context, conversations, memory, and connected tools together so you do not have to start from zero.", aliases: ["what does it do","how does it work","what is it for"] },
    { id: "core.get_started", category: "getting_started", question: "How do I get started?", answer: "Download TerminalSync, sign in, and create your first workspace. The included AI is ready to chat; you can add files, links, or tools from Context whenever you want to work with information from your business.", aliases: ["how to start","first step","install"] },
    { id: "sync.move_between_devices", category: "workspaces_sync", question: "How do I move my work to another device?", answer: "Stop writing on the first device, wait for it to sync, then open, import, or resume that workspace on the second. Your project history and context come with it.", aliases: ["sync between devices","switch devices","continue on another computer"] },
    { id: "context.what_is", category: "context", question: "What is Context?", answer: "Context is where you see what information the AI can use in a workspace: conversations, documents, notes, rules, links, videos, memory, and produced material. It also keeps connected tools separate so you do not confuse a connection with a document the AI has already read. Controls such as pause, remove, or ask only about one source appear only when that source supports them.", aliases: ["what is the AI using","add context","context panel"] },
    { id: "memory.persistent", category: "workspaces_sync", question: "Does the AI remember my project?", answer: "Yes. TerminalSync syncs each project's memory: previous conversations and notes about how you work. When you open the same project on another device, you can continue with that context instead of explaining it again.", aliases: ["persistent memory","the AI remembers","I do not want to repeat context"] },
    { id: "context.web_and_youtube", category: "context", question: "Can I add a web page or a YouTube video?", answer: "Yes. In Context, choose “Web and videos,” paste the link, and wait for its text to be saved. A YouTube video works when it has a caption track the app can read; otherwise the panel should explain the problem instead of pretending it read the video.", aliases: ["read a video","add a URL","web and videos"] },
    { id: "context.share_to_workspace", category: "context", question: "Can I send context to another workspace?", answer: "Yes. Select sources that can be shared and send them to another workspace you own. They should appear in the destination as usable copies; removing the destination copy should not delete the original source.", aliases: ["share context","send documents to another workspace","send material"] },
    { id: "privacy.what_is_encrypted", category: "privacy", question: "What is protected?", answer: "Your secrets, credentials, profile, memory, and AI conversations are encrypted on your device before they sync. Your project files go to your own cloud account in their original format; do not confuse that path with the encryption applied to conversations and secrets.", aliases: ["security","encryption","can you see my files","privacy"] },
    { id: "workspaces.offline", category: "workspaces_sync", question: "What happens if I lose internet?", answer: "Local work can continue offline, and cloud sync resumes when you are back online. Features that need an external service or an AI reply may wait for the connection to return.", aliases: ["works offline","without internet","offline"] },
    { id: "catalog.what_are_connectors", category: "integrations", question: "What is a connector and what do I need to use one?", answer: "A connector links the AI to a service you already use, such as email, calendars, documents, a CRM, or payments. You add it from Integrations, and it may require an API key, OAuth, sign-in, an account, or service permissions. The screen should tell you what is missing.", aliases: ["integrations","connect Gmail","connect tools","what permissions are needed"] },
    { id: "catalog.five_sections", category: "catalog", question: "What can I find in Integrations?", answer: "The explorer is organized into five visible groups: Kits, Plugins, Connectors, Skills, and CLI Tools. Kits and Plugins combine pieces for a job; Connectors link services; Skills add a way of working; and CLI Tools cover technical tasks that need installation and sign-in.", aliases: ["kits","plugins","CLI tools","what is in the catalog","skills"] },
    { id: "catalog.kits_are_included", category: "catalog", question: "Do Kits cost extra?", answer: "Available Kits are shown as free and included with the plan; some are marked Coming soon and should not be counted as ready. Any cost or account needed for an external service inside the Kit still depends on that service.", aliases: ["free kits","kit pricing","packs"] },
    { id: "plans.current_pricing", category: "plans_billing", question: "How much does it cost?", answer: "Current plans and any trial availability are shown on the pricing screen and checkout. Review the current plan, currency, and terms before paying; existing accounts should not assume a trial restarts when changing plans.", aliases: ["price","plans","free trial","monthly","billing"] },
    { id: "platforms.launch_scope", category: "platforms", question: "Which devices are supported right now?", answer: "The current launch is for macOS. Windows is collecting interested users while installer signing is completed, and Linux is not part of this launch's public promise. Do not present those platforms as active downloads until the release direction changes.", aliases: ["does it work on Windows","does it work on Linux","Mac download","platforms"] },
    { id: "support.when_human", category: "support", question: "What should I do if something fails?", answer: "First read the app's notice and retry only if the action tells you to. If there is a risk of data loss, a charge, a security problem, or repeated sync failure, ask for human help and keep the error message without sharing secrets.", aliases: ["help","it does not work","talk to a person","lost data"] },
  ],
};

const HOME_IDS = new Set(["core.what_is","core.get_started","sync.move_between_devices","context.what_is","memory.persistent","context.web_and_youtube","context.share_to_workspace","privacy.what_is_encrypted","catalog.what_are_connectors","platforms.launch_scope"]);

export function getPublicFaq(locale: Locale): readonly PublicFaqItem[] {
  return FAQ_BY_LOCALE[locale];
}

export function getHomeFaq(locale: Locale): readonly PublicFaqItem[] {
  return FAQ_BY_LOCALE[locale].filter((item) => HOME_IDS.has(item.id));
}
